[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --html=reports/report.html --self-contained-html --base-url=https://eventhub.rahulshettyacademy.com
markers =
    ui: UI tests
    api: API tests
    hybrid: Hybrid tests
    positive: Positive test cases
    negative: Negative test cases
